### ISSUE TITLE
[Code] Flow of the scenes

### ISSUE THREAD

**Issue by ghost** [caranha/BordeauxTsukuba2017#5]
Script the steps of the scenes (succession of dialogues, of places to visit, of narrations, ...)

**Comment by VietKhangLH** [comment]
Done !!
Using a kind of State Pattern
Each StoryState will have a process method to call, and the Context is defined by a StoryTeller

The StoryTeller actually looks at player interactions and will tell the story according to the current state.

(How to know the next state ? it's predefined on each StoryState)
