### ISSUE TITLE
Chat bubbles

### ISSUE THREAD

**Issue by ghost** [caranha/BordeauxTsukuba2017#6]

**Comment by VietKhangLH** [comment]
Done : 

/**
 * When a entity talk, display a chat bubble
 * If he talks alone, this bubble appear above him
 * Else, it shows in the other side of his interlocutor
 *
 * Public method :
 * + update() (from Obserrver)
 * + render(Batch) (Main method)
 * + dispose() (from disposable)
 */

Only need an Observable Message from Model at instanciation
